services:
  backend:
    build:
      context: ./apps/api/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    networks:
      - front-tier
      - back-tier

  frontend:
    build:
      context: ./apps/web/
    networks:
      - front-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${DB_USER}"
      PGUSER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./configs/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - back-tier
  
  proxy:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./configs/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - frontend 
    ports: 
      - "${port}:80"
    expose:
      - "80"
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  db-data:
